language: node_js
node_js:
  - "8"

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: npm release
      node_js: "8"
      script: echo "Deploying to npm ..."
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm prune --production
          - npx semantic-release
