language: node_js
node_js:
  - "10"
  - "12"
  - "14"

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: npm release
      node_js: "12"
      script: echo "Deploying to npm ..."
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
